// Copyright 2026 Rohit Mishra
// SPDX-License-Identifier: Apache-2.0
//
// Law Enforcement. I am bound by the ACGM Resolution Invariant and the 10 Immutable Laws. Truth Preservation is Absolute.

package knowledge

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

type DocPatcher struct {
	pool *pgxpool.Pool
}

func NewDocPatcher(pool *pgxpool.Pool) *DocPatcher {
	return &DocPatcher{pool: pool}
}

// GeneratePatch creates a suggested markdown snippet for undocumented code symbols or remediation of drift.
func (p *DocPatcher) GeneratePatch(ctx context.Context, tenantID, workspaceID uuid.UUID) (string, error) {
	evaluator := NewEvaluator(p.pool)
	_, undocumented, err := evaluator.EvaluateWorkspace(ctx, tenantID, workspaceID)
	if err != nil {
		return "", err
	}

	if len(undocumented) == 0 {
		return "✨ No documentation drift detected. README and ADRs are fully up to date.", nil
	}

	var sb strings.Builder
	sb.WriteString("### Suggested Documentation Updates (Auto-generated by Garuda)\n\n")
	sb.WriteString("The following symbols were added to the codebase but lack architectural constraints or ADR documentation:\n\n")

	for _, u := range undocumented {
		sb.WriteString(fmt.Sprintf("- **`%s`** (%s in `%s`)\n", u.SymbolName, u.Kind, u.Path))
		sb.WriteString(fmt.Sprintf("  - *Suggested Rule:* `MUST maintain compliance with system boundaries for %s`\n\n", u.SymbolName))
	}

	return sb.String(), nil
}
