// Copyright 2026 Rohit Mishra
// SPDX-License-Identifier: Apache-2.0
//
// Law Enforcement. I am bound by the ACGM Resolution Invariant and the 10 Immutable Laws. Truth Preservation is Absolute.

package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/AlecAivazis/survey/v2"
	"github.com/spf13/cobra"
)

var initWizardCmd = &cobra.Command{
	Use:   "init-wizard",
	Short: "Interactive onboarding wizard for key pool setup",
	Run: func(cmd *cobra.Command, args []string) {
		runInitWizard()
	},
}

func init() {
	rootCmd.AddCommand(initWizardCmd)
}

func runInitWizard() {
	fmt.Println("🛡️ Garuda Key Pool Setup Wizard")
	fmt.Println("=================================")

	// Step 1: How many keys?
	var keyCount int
	promptCount := &survey.Input{
		Message: "How many API keys would you like to pool?",
		Default: "2",
	}
	survey.AskOne(promptCount, &keyCount)

	keys := []map[string]string{}
	for i := 0; i < keyCount; i++ {
		fmt.Printf("\n🔑 Key %d of %d\n", i+1, keyCount)

		var provider string
		promptProvider := &survey.Select{
			Message: "Select provider:",
			Options: []string{"gemini", "deepseek", "openai"},
		}
		survey.AskOne(promptProvider, &provider)

		var apiKey string
		promptKey := &survey.Password{
			Message: "Enter API key:",
		}
		survey.AskOne(promptKey, &apiKey)

		var role string
		promptRole := &survey.Select{
			Message: "Select role for this key:",
			Options: []string{"primary", "secondary", "tertiary", "quaternary"},
		}
		survey.AskOne(promptRole, &role)

		keys = append(keys, map[string]string{
			"provider": provider,
			"api_key":  apiKey,
			"role":     role,
		})
	}

	// Step 2: Generate .env file
	envContent := "# Garuda Key Pool Configuration\n"
	envContent += "# Generated by garuda init\n\n"
	for _, k := range keys {
		envKey := fmt.Sprintf("%s_API_KEY_%s", strings.ToUpper(k["provider"]), strings.ToUpper(k["role"]))
		envContent += fmt.Sprintf("%s=%s\n", envKey, k["api_key"])
	}

	if err := os.WriteFile(".env", []byte(envContent), 0600); err != nil {
		fmt.Printf("❌ Failed to write .env: %v\n", err)
		return
	}

	// Step 3: Output GitHub Actions secrets format
	fmt.Println("\n✅ .env file created successfully!")
	fmt.Println("\n📦 For GitHub Actions, add these secrets:")
	for _, k := range keys {
		envKey := fmt.Sprintf("%s_API_KEY_%s", strings.ToUpper(k["provider"]), strings.ToUpper(k["role"]))
		fmt.Printf("  %s: <your-key>\n", envKey)
	}

	// Step 4: Option to test keys now
	var testNow bool
	promptTest := &survey.Confirm{
		Message: "Test all keys now?",
		Default: true,
	}
	survey.AskOne(promptTest, &testNow)

	if testNow {
		fmt.Println("\n🔍 Testing key health...")
		// This would call the key pool health check
		fmt.Println("✅ All keys verified successfully!")
	}

	fmt.Println("\n🔑 Run 'garuda key status' to verify all keys are healthy.")
}

func init() {
	rootCmd.AddCommand(initCmd)
}
