-- Workspaces
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE workspaces ALTER COLUMN root_path DROP NOT NULL;
ALTER TABLE workspaces ALTER COLUMN root_path SET DEFAULT '.';
ALTER TABLE workspaces ADD COLUMN IF NOT EXISTS is_go_work BOOLEAN DEFAULT false;

-- Repositories
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS name TEXT DEFAULT 'primary';
ALTER TABLE repositories ALTER COLUMN name DROP NOT NULL;
ALTER TABLE repositories ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'local';
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS url TEXT;
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS default_branch TEXT DEFAULT 'main';
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'go';
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS module_path TEXT DEFAULT '';
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS enabled BOOLEAN DEFAULT true;
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS analysis_status TEXT DEFAULT 'pending';
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS current_commit TEXT;
ALTER TABLE repositories ADD COLUMN IF NOT EXISTS last_analyzed_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS uq_repositories_workspace_url ON repositories (workspace_id, url);

-- Entities
ALTER TABLE entities ADD COLUMN IF NOT EXISTS analysis_id UUID;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE entities ALTER COLUMN file DROP NOT NULL;
ALTER TABLE entities ALTER COLUMN file SET DEFAULT '';
ALTER TABLE entities ALTER COLUMN package DROP NOT NULL;
ALTER TABLE entities ALTER COLUMN package SET DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS doc_comment TEXT;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS signature TEXT;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS fields JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS methods JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS parameters JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS returns JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'public';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS hash TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS is_exported BOOLEAN DEFAULT true;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS is_test BOOLEAN DEFAULT false;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS is_generated BOOLEAN DEFAULT false;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS source_code TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS doc TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS comments TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS ast_hash TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS content_hash TEXT DEFAULT '';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS type_params JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS implements JSONB DEFAULT '[]'::jsonb;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Claims
ALTER TABLE claims ADD COLUMN IF NOT EXISTS analysis_id UUID;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS workspace_id UUID;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS repository_id UUID;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION DEFAULT 1.0;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS evidence JSONB DEFAULT '{}'::jsonb;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb;
ALTER TABLE claims ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();