-- Copyright 2026 Rohit Mishra
-- SPDX-License-Identifier: Apache-2.0
--
-- 073_delete_workspace_core_test_residue.sql
--
-- Deletes 16 rows in workspaces named 'workspace-core' that were
-- created by TestTenantIsolation_ConcurrentSymbolCacheCollisions
-- before it was given a t.Cleanup handler. Each row carries a
-- distinct random tenant_id generated by the test. The rows were
-- never cleaned up.
--
-- The corresponding symbol_cache rows for those tenants are deleted
-- in the same transaction, since symbol_cache has no FK to workspaces
-- and does not cascade.
--
-- Guards:
--   - refuses if any workspace-core row belongs to the canonical tenant
--   - refuses if any workspace-core row has a repository referencing it
-- Both guards preserve a future workspace-core that was created
-- intentionally under the canonical tenant.

DO $$
DECLARE
  victim_tenants uuid[];
  victim_count   INT;
  canonical_hits INT;
  repo_hits      INT;
BEGIN
  SELECT array_agg(DISTINCT tenant_id), COUNT(*)
    INTO victim_tenants, victim_count
    FROM workspaces
   WHERE name = 'workspace-core';

  IF victim_count = 0 THEN
    RAISE NOTICE '073: no workspace-core rows present; nothing to do';
    RETURN;
  END IF;

  SELECT COUNT(*) INTO canonical_hits
    FROM workspaces
   WHERE name = 'workspace-core'
     AND tenant_id = '00000000-0000-0000-0000-000000000001';
  IF canonical_hits > 0 THEN
    RAISE EXCEPTION '073: refusing to delete % workspace-core row(s) under the canonical tenant', canonical_hits;
  END IF;

  SELECT COUNT(*) INTO repo_hits
    FROM repositories r
    JOIN workspaces w ON w.id = r.workspace_id
   WHERE w.name = 'workspace-core';
  IF repo_hits > 0 THEN
    RAISE EXCEPTION '073: refusing to delete: % repositories reference workspace-core', repo_hits;
  END IF;

  RAISE NOTICE '073: deleting residue for % tenants: %', victim_count, victim_tenants;

  DELETE FROM symbol_cache WHERE tenant_id = ANY(victim_tenants);
  RAISE NOTICE '073: symbol_cache rows removed for % tenants', array_length(victim_tenants, 1);

  DELETE FROM workspaces WHERE name = 'workspace-core';
  RAISE NOTICE '073: workspaces rows removed (cascades to workspace_modules, cross_module_edges, runtime_observations)';
END $$;