package selfdescribe

import (
	"strings"
	"time"
)

// GenerateMarkdown produces a README skeleton from the self-description.
func GenerateMarkdown(desc *SelfDescription) string {
	var b strings.Builder

	b.WriteString("# " + desc.Product.Name + "\n\n")
	b.WriteString("> " + desc.Product.Tagline + "\n\n")
	b.WriteString("Generated: " + time.Now().Format(time.RFC3339) + "\n\n")
	b.WriteString("---\n\n")

	b.WriteString("## Overview\n\n")
	b.WriteString(desc.Product.Description + "\n\n")

	b.WriteString("## Capabilities\n\n")
	b.WriteString("| Capability | Status | Command | Source |\n")
	b.WriteString("|------------|--------|---------|--------|\n")
	for _, cap := range desc.Capabilities {
		cmd := cap.Command
		if cmd == "" {
			cmd = "-"
		}
		b.WriteString("| " + cap.Name + " | " + cap.Status + " | `" + cmd + "` | " + cap.Source + " |\n")
	}
	b.WriteString("\n")

	b.WriteString("## CLI Commands\n\n")
	b.WriteString("```bash\n")
	for _, cmd := range desc.CLI.Commands {
		b.WriteString("garuda " + cmd.Name + "  # " + cmd.Description + "\n")
	}
	b.WriteString("```\n\n")

	b.WriteString("## Semantic Model\n\n")
	b.WriteString("- **Entities:** " + string(rune(desc.Semantic.Entities)) + "\n")
	b.WriteString("- **Relationships:** " + string(rune(desc.Semantic.Relationships)) + "\n")
	b.WriteString("- **Evidence:** " + string(rune(desc.Semantic.Evidence)) + "\n")
	b.WriteString("- **Lineage:** " + map[bool]string{true: "✅", false: "❌"}[desc.Semantic.Lineage] + "\n\n")

	b.WriteString("## Trust & Integrity\n\n")
	b.WriteString("- **Immutable Ledger:** " + map[bool]string{true: "✅", false: "❌"}[desc.Trust.ImmutableLedger] + "\n")
	b.WriteString("- **Merkle Root:** `" + desc.Trust.MerkleRoot + "`\n")
	b.WriteString("- **Revisions:** " + string(rune(desc.Trust.RevisionCount)) + "\n\n")

	if desc.Roadmap.CurrentPhase != "" {
		b.WriteString("## Roadmap\n\n")
		b.WriteString("- **Current Phase:** " + desc.Roadmap.CurrentPhase + "\n")
		b.WriteString("- **Next Phase:** " + desc.Roadmap.NextPhase + "\n")
		b.WriteString("- **Phases:** " + strings.Join(desc.Roadmap.Phases, ", ") + "\n\n")
	}

	b.WriteString("## Installation\n\n")
	b.WriteString("```bash\n")
	b.WriteString("go install github.com/myshra777-ai/garuda@latest\n")
	b.WriteString("```\n\n")

	b.WriteString("## Quick Start\n\n")
	b.WriteString("```bash\n")
	b.WriteString("garuda analyze .\n")
	b.WriteString("garuda inspect <entity>\n")
	b.WriteString("garuda graph . --open\n")
	b.WriteString("```\n\n")

	b.WriteString("## Contributing\n\n")
	b.WriteString("1. Fork the repository\n")
	b.WriteString("2. Create a feature branch\n")
	b.WriteString("3. Submit a pull request\n\n")

	b.WriteString("---\n\n")
	b.WriteString("*Generated by `garuda self describe` on " + time.Now().Format(time.RFC3339) + "*\n")

	return b.String()
}
