#!/usr/bin/env python3
"""
doc_verify_test.py — reproducible extraction → verification loop.

Purpose: exercise the one predicate the verifier checks (CALLS) end to
end. A document goes in, claims come out, the verifier flips claims to
SUPPORTED when the static graph contains the edge the claim describes.

This is a test harness, not a code change. It exercises the ingest and
verify paths. It does not modify the parser, the evaluator, or the
store.

Method:

  1. Pick one real CALLS edge from the workspace. It becomes the
     subject and object of the first bullet in the test ADR.

  2. Pick one real exported entity. It becomes the subject of the
     second bullet, whose object is an invented name.

  3. The third bullet names two invented entities.

  4. Write the test ADR to a temp file, run `garuda docs ingest`, run
     `garuda docs verify`, then count document_claims rows by status.

  5. Assert the expected shape: the real edge flips SUPPORTED, the
     other two stay UNVERIFIED. Exit 0 if the shape holds, 1 if not.

Exit codes:
  0 — expected split observed
  1 — observed split differs from expected
  2 — environment failure (no database, no binary, no workspace)

Usage:
  DATABASE_URL=... python3 scripts/doc_verify_test.py

Environment:
  GARUDA_BIN        default ./bin/garuda
  GARUDA_WORKSPACE  default go-validation-10
  DATABASE_URL      required
"""

import os
import subprocess
import sys
import tempfile

BIN = os.environ.get("GARUDA_BIN", "./bin/garuda")
WORKSPACE = os.environ.get("GARUDA_WORKSPACE", "go-validation-10")
DATABASE_URL = os.environ.get("DATABASE_URL", "")

if not DATABASE_URL:
    print("DATABASE_URL is required", file=sys.stderr)
    sys.exit(2)


def psql(query):
    """Run one SQL statement and return its trimmed stdout."""
    cmd = ["psql", DATABASE_URL, "-tAc", query]
    out = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return out.stdout.strip()


def workspace_id_subquery():
    """Return the workspace id for the named workspace as a subquery."""
    return f"(SELECT id FROM workspaces WHERE name = '{WORKSPACE}' ORDER BY updated_at DESC LIMIT 1)"


def pick_real_edge():
    """Return (from_name, to_name) for one real CALLS edge in the workspace."""
    ws = workspace_id_subquery()
    query = f"""
        SELECT e1.name || '|' || e2.name
          FROM claims c
          JOIN entities e1 ON e1.id = c.from_entity_id
          JOIN entities e2 ON e2.id = c.to_entity_id
         WHERE c.workspace_id = {ws}
           AND c.claim_type = 'CALLS'
           AND e1.is_exported = true
           AND e2.is_exported = true
           AND e1.kind IN ('function', 'method')
           AND e2.kind IN ('function', 'method')
           AND LENGTH(e1.name) BETWEEN 3 AND 40
           AND LENGTH(e2.name) BETWEEN 3 AND 40
         LIMIT 1
    """
    row = psql(query)
    if not row:
        print(f"No CALLS edge found in workspace {WORKSPACE}", file=sys.stderr)
        sys.exit(2)
    return row.split("|", 1)


def pick_real_entity():
    """Return the name of one real exported function in the workspace."""
    ws = workspace_id_subquery()
    query = f"""
        SELECT name
          FROM entities
         WHERE workspace_id = {ws}
           AND kind IN ('function', 'method')
           AND is_exported = true
           AND LENGTH(name) BETWEEN 3 AND 40
         ORDER BY random()
         LIMIT 1
    """
    row = psql(query)
    if not row:
        print(f"No exported entity found in workspace {WORKSPACE}", file=sys.stderr)
        sys.exit(2)
    return row


def write_test_doc(path, real_edge, real_entity):
    src, dst = real_edge
    content = f"""# Doc verify test

Synthetic ADR for the extraction to verification loop. This file is
generated by scripts/doc_verify_test.py and is safe to delete.

## Decision

- `{src}` must call `{dst}`
- `{real_entity}` must call `NonexistentTargetXYZ`
- `NonexistentCallerABC` must call `NonexistentTargetDEF`

## Context

The first bullet names a real edge in the workspace. It should flip
to SUPPORTED. The second names a real entity but an invented object;
it should stay UNVERIFIED. The third names nothing real.
"""
    with open(path, "w") as f:
        f.write(content)


def run_ingest(path):
    env = {**os.environ, "GARUDA_WORKSPACE": WORKSPACE}
    result = subprocess.run(
        [BIN, "docs", "ingest", path],
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("ingest failed:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(2)
    return result.stdout


def run_verify():
    env = {**os.environ, "GARUDA_WORKSPACE": WORKSPACE}
    result = subprocess.run(
        [BIN, "docs", "verify"],
        env=env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("verify failed:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(2)
    return result.stdout


def count_status(path):
    ws = workspace_id_subquery()
    query = f"""
        SELECT status || '|' || COUNT(*)::text
          FROM document_claims
         WHERE workspace_id = {ws}
           AND document_path = '{path}'
         GROUP BY status
    """
    rows = psql(query).splitlines()
    return dict(r.split("|", 1) for r in rows if r)


def main():
    print(f"Workspace:   {WORKSPACE}")
    print(f"Binary:      {BIN}")
    print(f"Database:    {DATABASE_URL[:40]}...")
    print()

    real_edge = pick_real_edge()
    real_entity = pick_real_entity()
    print(f"Real edge:   {real_edge[0]} -> {real_edge[1]}")
    print(f"Real entity: {real_entity}")
    print()

    with tempfile.NamedTemporaryFile(
        suffix=".md", prefix="garuda-doc-verify-", delete=False
    ) as f:
        path = f.name

    try:
        write_test_doc(path, real_edge, real_entity)
        print(f"Wrote test ADR: {path}")
        print()

        print("─── garuda docs ingest ───")
        print(run_ingest(path))
        print("─── garuda docs verify ───")
        print(run_verify())

        counts = count_status(path)
        supported = int(counts.get("SUPPORTED", 0))
        unverified = int(counts.get("UNVERIFIED", 0))
        contradicted = int(counts.get("CONTRADICTED", 0))

        print("═══ Status distribution ═══")
        print(f"  SUPPORTED     {supported}")
        print(f"  UNVERIFIED    {unverified}")
        print(f"  CONTRADICTED  {contradicted}")
        print()

        if supported >= 1 and unverified >= 2 and contradicted == 0:
            print("═══ PASS ═══")
            sys.exit(0)

        print("═══ FAIL ═══")
        print("Expected: at least 1 SUPPORTED, at least 2 UNVERIFIED, 0 CONTRADICTED")
        sys.exit(1)
    finally:
        os.unlink(path)


if __name__ == "__main__":
    main()