#!/usr/bin/env python3
"""
Garuda AI README Updater
Uses Gemini API to analyze git diff and update README.md between <!-- FEATURES_START --> and <!-- FEATURES_END --> markers.
"""

import os
import sys
import json
import subprocess
import re
from datetime import datetime
import google.generativeai as genai

# Configuration
README_PATH = "README.md"
FEATURES_START = "<!-- FEATURES_START -->"
FEATURES_END = "<!-- FEATURES_END -->"

def get_git_diff():
    """Get the diff of the latest commit."""
    try:
        # Get the list of changed files
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD~1", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        )
        changed_files = result.stdout.strip().split("\n")
        
        # Get the actual diff
        diff_result = subprocess.run(
            ["git", "diff", "HEAD~1", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        )
        return diff_result.stdout, changed_files
    except subprocess.CalledProcessError as e:
        print(f"❌ Git diff failed: {e}")
        return "", []

def get_project_summary():
    """Get project metadata."""
    # Get latest version from go.mod
    try:
        result = subprocess.run(
            ["grep", "module", "go.mod"],
            capture_output=True,
            text=True,
            check=True
        )
        module = result.stdout.strip()
    except:
        module = "github.com/myshra777-ai/garuda"
    
    # Get commit count
    try:
        result = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        )
        commit_count = result.stdout.strip()
    except:
        commit_count = "0"
    
    # Get latest commit message
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--pretty=format:%s"],
            capture_output=True,
            text=True,
            check=True
        )
        latest_commit = result.stdout.strip()
    except:
        latest_commit = "Initial commit"
    
    # List key directories
    dirs = ["cmd", "internal", "migrations", "deploy"]
    structure = []
    for d in dirs:
        try:
            result = subprocess.run(
                ["ls", "-la", d],
                capture_output=True,
                text=True,
                check=True
            )
            structure.append(f"### {d}/\n{result.stdout[:500]}...")
        except:
            pass
    
    return {
        "module": module,
        "commit_count": commit_count,
        "latest_commit": latest_commit,
        "structure": "\n".join(structure)
    }

def detect_capabilities(diff_text):
    """Extract capabilities from git diff using AI."""
    genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
    model = genai.GenerativeModel('gemini-2.0-flash')
    
    prompt = f"""
You are analyzing a Git diff for the Garuda project – an Organizational Intelligence Runtime for AI agents.

Analyze the following diff and identify NEW capabilities, features, or endpoints introduced.
Only list what is being ADDED or CHANGED in this commit.

Provide a concise summary of what the README should mention as NEW features (maximum 5 bullet points).

**Diff:**
{diff_text[:4000]}  # Truncate to fit context

Output format: A numbered list of new features. Example:
1. Added new endpoint /api/v1/checkpoints for agent state persistence
2. Integrated telemetry collector with async batching
3. Improved contradiction engine with quarantine resolution
"""
    
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"❌ AI processing failed: {e}")
        return "No new capabilities detected."

def update_readme(new_features):
    """Update README.md between feature markers."""
    if not os.path.exists(README_PATH):
        print(f"❌ README.md not found at {README_PATH}")
        return False
    
    with open(README_PATH, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Check if markers exist
    if FEATURES_START not in content or FEATURES_END not in content:
        print("⚠️ Feature markers not found in README. Please add:")
        print(f"{FEATURES_START}\n{FEATURES_END}")
        return False
    
    # Build new feature section
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    new_section = f"""
{FEATURES_START}
### 🚀 Latest Capabilities (Updated {timestamp})

{new_features}

---
_This section is auto-generated by AI from the latest commits._
{FEATURES_END}
"""
    
    # Replace between markers
    pattern = re.compile(
        rf"{re.escape(FEATURES_START)}.*?{re.escape(FEATURES_END)}",
        re.DOTALL
    )
    updated_content = pattern.sub(new_section, content)
    
    with open(README_PATH, 'w', encoding='utf-8') as f:
        f.write(updated_content)
    
    return True

def main():
    print("🤖 Garuda AI README Updater")
    print("=" * 40)
    
    # Check API key
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ GEMINI_API_KEY environment variable not set")
        sys.exit(1)
    
    # Get diff
    print("📥 Analyzing latest commit...")
    diff_text, changed_files = get_git_diff()
    
    if not diff_text:
        print("ℹ️ No changes detected, skipping update")
        sys.exit(0)
    
    print(f"📄 Changed files: {len(changed_files)}")
    for f in changed_files[:5]:
        print(f"  - {f}")
    
    # Detect new capabilities
    print("🧠 Processing with AI...")
    new_features = detect_capabilities(diff_text)
    
    print(f"✅ New capabilities detected:\n{new_features}")
    
    # Update README
    if update_readme(new_features):
        print("✅ README updated successfully!")
        
        # Stage the change
        subprocess.run(["git", "add", README_PATH], capture_output=True)
        print("📦 README staged for commit")
    else:
        print("❌ Failed to update README")
        sys.exit(1)

if __name__ == "__main__":
    main()